# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c63d04ea1c11bc5e4c0771bd5967c0937520d646fe1499a903bb0f2120edc0a9d240b905621ab4dadd1c6c4e1c95f85588398f66d397ea57ae3ce996f225579

test:
  secret_key_base: acee85d72a70e33a818cb7f9ab0da2de9e839a399996fb1423e6d132aaad3c016a5600bf0ad3e0d92073e82e409c2fc05cc5e16f8d0c950f86496ade8bbfaeaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
